# Generated by Django 5.1.5 on 2025-01-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='UploadModel',
        ),
    ]
