# Generated by Django 5.1.5 on 2025-01-24 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_files_delete_uploadmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
    ]
